### ISSUE TITLE
Unable parse Register message

### ISSUE THREAD

**Issue by kingecg** [kbalt/ezk#10]
I use this lib in SIP server. But I found it can not parse Register message sent by a client

**Comment by kingecg** [comment]
REGISTER sip:34020000002000000001@3402000000 SIP/2.0
Via: SIP/2.0/UDP 192.168.10.8:60719;rport=60719;branch=z9hG4bK1377739937
Max-Forwards: 70
Contact: <sip:34020000002000000719@192.168.10.8:60719>
To: <sip:34020000002000000719@3402000000>
From: <sip:34020000002000000719@3402000000>;tag=1534571172
Call-ID: 1566767517
CSeq: 1 REGISTER
Expires: 3600
User-Agent: IP Camera
Content-Length: 0

**Comment by kbalt** [comment]
Hi,

this was an issue where hostnames where parsed incorrectly.

I have improved the parsing (see commit 95af4d47c87cd102baa9e3cdf02521ec89053535) and released a new version `0.1.1` of `ezk-sip-types` which contains the fix.
