### ISSUE TITLE
Unhandled panicking in create_reg_interval function in ezk_sip_ua

### ISSUE THREAD

**Issue by tobiasfunke1** [kbalt/ezk#17]
Hi,

I came across a bug in your ezk_sip_ua crate. It is an unhandled panicking in the `create_reg_interval` function.

If the period duration is smaller 10 seconds the program will panic at this line: https://github.com/kbalt/ezk/blob/main/crates/sip-ua/src/register/mod.rs#L104C1-L104C51

Change [your Register example](https://github.com/kbalt/ezk/blob/main/crates/sip-ua/src/register/mod.rs) code like this to reproduce the bug:
```
...
    let mut registration = Registration::new(
        NameAddr::uri(id),
        NameAddr::uri(contact),
        registrar.into(),
        Duration::from_secs(5),  // <-- duration is smaller than 10 secs
    );
...
```
I haven't tested it yet, but this error can possibly occur if the SIP response contains an Expire header with less than 10 seconds and someone calls the `receive_success_response` function on the response because the faulty function is also called there.

A solution could be the `checked_sub` function, which can be used to check if the resulting duration of a subtraction would be negative/overflow and handle the problem by somehow. Or use the `saturating_sub` function.

**Comment by kbalt** [comment]
Hi, thanks for finding!

I added a minimum value for `period` to work around this issue in https://github.com/kbalt/ezk/commit/6bc07a154e0b54f0a9d482f6b8fa526cbd97e956

**Comment by kbalt** [comment]
Just out of curiosity, do you have a scenario where an interval as short as 5 seconds is required? Usually the expiry value with common registrars is at least 5mins.

**Comment by tobiasfunke1** [comment]
I just stumbled across it when I was writing tests for an app that uses your crate.
