### ISSUE TITLE
Improvement: Bind port for TcpConnector

### ISSUE THREAD

**Issue by tobiasfunke1** [kbalt/ezk#41]
Hi,

for some use cases (e.g. IPsec) it would be nice to bind a non-listen TCP socket to a non-ephemeral port.

I think we only need to create a socket and bind it to a specific port (or `SocketAddr`) before connecting to a target.

@kbalt What do you think?

**Comment by kbalt** [comment]
Closed by https://github.com/kbalt/ezk/pull/42
